# Generated by Django 2.0 on 2018-01-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=48)),
                ('balance', models.FloatField()),
                ('payments_to_date', models.FloatField()),
                ('fees_to_date', models.FloatField()),
                ('net_earnings', models.FloatField()),
                ('gross_earnings', models.FloatField()),
                ('net_change', models.FloatField()),
                ('time_change', models.FloatField()),
                ('earning_rate', models.FloatField()),
                ('balance_history', models.ManyToManyField(to='Tracking.BalanceLog')),
                ('payment_history', models.ManyToManyField(to='Tracking.PaymentLog')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('power_draw', models.FloatField()),
                ('running_cost', models.FloatField()),
                ('purchase_cost', models.FloatField()),
                ('gtx1060', models.IntegerField(default=0)),
                ('gtx1070', models.IntegerField(default=0)),
                ('gtx1070ti', models.IntegerField(default=0)),
                ('gtx1080', models.IntegerField(default=0)),
                ('gtx1080ti', models.IntegerField(default=0)),
                ('activity_log', models.ManyToManyField(to='Tracking.WorkerActivityLog')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='workers',
            field=models.ManyToManyField(to='WAW.Worker'),
        ),
    ]
