# Generated by Django 2.0 on 2018-01-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance_history',
            field=models.ManyToManyField(blank=True, to='Tracking.BalanceLog'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='earning_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='fees_to_date',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='gross_earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='net_change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='net_earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='payment_history',
            field=models.ManyToManyField(blank=True, to='Tracking.PaymentLog'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='payments_to_date',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='time_change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='workers',
            field=models.ManyToManyField(blank=True, to='WAW.Worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='activity_log',
            field=models.ManyToManyField(blank=True, to='Tracking.WorkerActivityLog'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='power_draw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='purchase_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='running_cost',
            field=models.FloatField(default=0),
        ),
    ]
