# Generated by Django 2.0 on 2018-01-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAW', '0002_auto_20180128_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='earning_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='net_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='time_change',
            field=models.FloatField(null=True),
        ),
    ]
