# Generated by Django 2.0 on 2018-01-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeractivitylog',
            name='algorithms',
            field=models.ManyToManyField(blank=True, to='Tracking.AlgorithmLog'),
        ),
    ]
