# Generated by Django 2.0 on 2018-01-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_workeractivitylog_worker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmbalancelog',
            name='wallet_address',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancelog',
            name='wallet_address',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='wallet_address',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workeractivitylog',
            name='worker_name',
            field=models.CharField(max_length=32),
        ),
    ]
