# Generated by Django 2.0 on 2018-01-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_auto_20180128_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithmlog',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
