# Generated by Django 2.0 on 2018-01-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0005_auto_20180128_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmbalancelog',
            name='balance_change',
        ),
        migrations.RemoveField(
            model_name='algorithmbalancelog',
            name='time_change',
        ),
        migrations.AddField(
            model_name='balancelog',
            name='earning_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='net_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='time_change',
            field=models.FloatField(null=True),
        ),
    ]
