# Generated by Django 2.0 on 2018-01-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_auto_20180128_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmUtilisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_id', models.IntegerField()),
                ('algorithm_name', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
